/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TroubleshootRouteImport } from './routes/troubleshoot'
import { Route as MailRouteImport } from './routes/mail'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as EpubRouteImport } from './routes/epub'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpeechOptimizeRouteImport } from './routes/speech/optimize'

const TroubleshootRoute = TroubleshootRouteImport.update({
  id: '/troubleshoot',
  path: '/troubleshoot',
  getParentRoute: () => rootRouteImport,
} as any)
const MailRoute = MailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const EpubRoute = EpubRouteImport.update({
  id: '/epub',
  path: '/epub',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeechOptimizeRoute = SpeechOptimizeRouteImport.update({
  id: '/speech/optimize',
  path: '/speech/optimize',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/epub': typeof EpubRoute
  '/library': typeof LibraryRoute
  '/mail': typeof MailRoute
  '/troubleshoot': typeof TroubleshootRoute
  '/speech/optimize': typeof SpeechOptimizeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/epub': typeof EpubRoute
  '/library': typeof LibraryRoute
  '/mail': typeof MailRoute
  '/troubleshoot': typeof TroubleshootRoute
  '/speech/optimize': typeof SpeechOptimizeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/epub': typeof EpubRoute
  '/library': typeof LibraryRoute
  '/mail': typeof MailRoute
  '/troubleshoot': typeof TroubleshootRoute
  '/speech/optimize': typeof SpeechOptimizeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/epub'
    | '/library'
    | '/mail'
    | '/troubleshoot'
    | '/speech/optimize'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/epub'
    | '/library'
    | '/mail'
    | '/troubleshoot'
    | '/speech/optimize'
  id:
    | '__root__'
    | '/'
    | '/epub'
    | '/library'
    | '/mail'
    | '/troubleshoot'
    | '/speech/optimize'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EpubRoute: typeof EpubRoute
  LibraryRoute: typeof LibraryRoute
  MailRoute: typeof MailRoute
  TroubleshootRoute: typeof TroubleshootRoute
  SpeechOptimizeRoute: typeof SpeechOptimizeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/troubleshoot': {
      id: '/troubleshoot'
      path: '/troubleshoot'
      fullPath: '/troubleshoot'
      preLoaderRoute: typeof TroubleshootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail': {
      id: '/mail'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof MailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epub': {
      id: '/epub'
      path: '/epub'
      fullPath: '/epub'
      preLoaderRoute: typeof EpubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speech/optimize': {
      id: '/speech/optimize'
      path: '/speech/optimize'
      fullPath: '/speech/optimize'
      preLoaderRoute: typeof SpeechOptimizeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EpubRoute: EpubRoute,
  LibraryRoute: LibraryRoute,
  MailRoute: MailRoute,
  TroubleshootRoute: TroubleshootRoute,
  SpeechOptimizeRoute: SpeechOptimizeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
